apiVersion: v1
kind: Pod
metadata:
  name: trex-deployment
  annotations:
    k8s.v1.cni.cncf.io/networks: afxdp-network,afxdp-network
spec:
  containers:
  - name: trex
    image: shivank1128/trex
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: ["sleep 30000"]
    resources:
      requests:
        afxdp/myPool: '2'
      limits:
        afxdp/myPool: '2'
  restartPolicy: Never
