apiVersion: apps/v1
kind: Deployment
metadata:
  name: prox-deployment
  labels:
    app: trex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prox
  template:
    metadata:
      labels:
        app: prox
    spec:
      containers:
      - name: prox
        image: shivank1128/prox
        command: [ "/bin/bash", "-c", "--" ]
        args: ["sleep 10000"]
        ports:
        - containerPort: 4500
